### ISSUE TITLE
seems to be a bug

### ISSUE THREAD

**Issue by alexlib** [OpenPIV/openpiv_tk_gui#40] opened 2021-11-30 09:30 UTC
I installed a new openpivgui using pip. The openpiv version is 0.23.8 
even a single simplest run with general settings fails with openpiv.windef doesn't have some method "get_coordinates". Don't know what it means and didn't look deeper. But I replaced the openpiv version with the last I remembered as a working one - 0.23.6 (see also a post on our forum) and it works with the same images fine. 

We need to try to get some unit testing automatically running on openpivgui with every update of openpiv - I guess this will be a huge issue if we do not manage to sync the two. Let's talk? @eguvep

**Comment by alexlib** [comment] 2021-11-30 09:37
I guess this is a possible reason for a bug - https://github.com/OpenPIV/openpiv-python/commit/f6fde4634c1ceb9c03603cad248e1818ef889844 we merged @ErichZimmer changes to vectorized functions and rectangular windows and the method is now called `get_rect_coordinates` , though also `get_coordinates` exists
https://github.com/OpenPIV/openpiv-python/blob/25d9eddd9527a4bf67822a2670d297d68a1a70f1/openpiv/pyprocess.py#L64
https://github.com/OpenPIV/openpiv-python/blob/25d9eddd9527a4bf67822a2670d297d68a1a70f1/openpiv/pyprocess.py#L143

**Comment by eguvep** [comment] 2021-11-30 12:00
Yes, I had the same and other unsatisfying issues yesterday, as I tried to reproduce the error that had been reported via Google Groups. The GUI should of course work with the default parameters and the example images. This is currently not the case. I had at least three different errors (not in main thread, wrong number of cores, method not found, ...). Unfortunately it is winter term, I have very limited time to look into that.

**Comment by alexlib** [comment] 2021-11-30 13:04
> Yes, I had the same and other unsatisfying issues yesterday, as I tried to reproduce the error that had been reported via Google Groups. The GUI should of course work with the default parameters and the example images. This is currently not the case. I had at least three different errors (not in main thread, wrong number of cores, method not found, ...). Unfortunately it is winter term, I have very limited time to look into that.

@eguvep 
just click here https://github.com/OpenPIV/openpiv_tk_gui/pull/41

**Comment by ErichZimmer** [comment] 2021-12-01 19:31
I don't understand the main thread issue, but the `get_coordinates` error was somewhat a surprise. I tried to keep everything backwards compatible on the vectorized functions merge, but I guess I may have done something wrong. ?

**Comment by GregorBecker** [comment] 2021-12-01 21:03
On September 5, all get_coordinates calls in openpiv.windef were replaced by get_rect_coordinates. Could this be the cause of the error ?

**Comment by ErichZimmer** [comment] 2021-12-01 22:16
I just ran through `windef`, albeit quickly because I'm on a 15 minute break, and could not find an issue. This doesn't make sense to me unless the OpenPIV version isn't "clean". Never had an issue on my personal GUI either.

**Comment by alexlib** [comment] 2021-12-02 06:43
The workaround so far is to work with 0.23.6 version - GUI calls all work. 
Instead of rolling back the changes in 0.23.8 we can think of updating the GUI calls or adding to 0.23.9 the links to the modified namespace.

**Comment by ErichZimmer** [comment] 2021-12-11 03:08
Does the GUI still work without major bugs with OpenPIV-Python version 0.23.6?

**Comment by alexlib** [comment] 2022-01-29 07:17
resolved in the latest pull request #42 - would you @eguvep pull it and bump a version? 

there is another bug I think related to GUI only - add it as an issue

**Comment by ErichZimmer** [comment] 2022-06-20 07:17
fixed in #46

**Closed as completed by ErichZimmer** 2022-06-20 07:17 UTC
Labels: bug
